invenio_userprofiles/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
# Copyright (C) 2022 Northwestern University.
# Copyright (C) 2023-2024 Graz University of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Invenio module that adds userprofiles to the platform."""

from warnings import warn

from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_security.confirmable import send_confirmation_instructions
from invenio_db import db
from invenio_i18n import lazy_gettext as _

from .forms import PreferencesForm, VerificationForm, create_email_profile_form
from .models import UserProfileProxy


def create_blueprint(app):
    """Create blueprint."""
    blueprint = Blueprint(
        "invenio_userprofiles",
        __name__,
        template_folder="templates",
        url_prefix="/account/settings",
    )

    @blueprint.app_template_filter()
    def userprofile(value):
        """Retrieve user profile for a given user id."""
        warn("userprofile template filter is deprecated.", DeprecationWarning)
        return UserProfileProxy.get_by_userid(int(value))

    blueprint.add_url_rule("/profile", view_func=profile, methods=["GET", "POST"])

    return blueprint


@login_required
def profile():
    """View for editing a profile."""
    # Create forms
    verification_form = VerificationForm(formdata=None, prefix="verification")
    profile_form = profile_form_factory()
    preferences_form = PreferencesForm(
        formdata=None, obj=current_user, prefix="preferences"
    )

    # Pick form
    is_read_only = current_app.config.get("USERPROFILES_READ_ONLY", False)
    form_name = request.form.get("submit", None)
    if form_name == "profile" and not is_read_only:
        handle_form = handle_profile_form
        form = profile_form
    elif form_name == "verification":
        handle_form = handle_verification_form
        form = verification_form
    elif form_name == "preferences":
        handle_form = handle_preferences_form
        form = preferences_form
    else:
        form = None

    # Process form
    if form:
        form.process(formdata=request.form)
        if form.validate_on_submit():
            handle_form(form)
            return redirect(url_for(".profile"), code=303)  # this endpoint

    return render_template(
        current_app.config["USERPROFILES_PROFILE_TEMPLATE"],
        verification_form=verification_form,
        profile_form=profile_form,
        preferences_form=preferences_form,
    )


def profile_form_factory():
    """Create a profile form."""
    UserProfileForm = current_app.config.get("USERPROFILES_FORM_CLASS")
    EmailProfileForm = create_email_profile_form(UserProfileForm)
    if current_app.config["USERPROFILES_EMAIL_ENABLED"]:
        return EmailProfileForm(
            formdata=None,
            obj=current_user,
            prefix="profile",
        )
    else:
        return UserProfileForm(
            formdata=None,
            obj=current_user,
            prefix="profile",
        )


def handle_verification_form(form):
    """Handle email sending verification form."""
    send_confirmation_instructions(current_user)
    # NOTE: Flash message.
    flash(_("Verification email sent."), category="success")


def handle_profile_form(form):
    """Handle profile update form."""
    email_changed = False
    datastore = current_app.extensions["security"].datastore
    with db.session.begin_nested():
        if (
            current_app.config["USERPROFILES_EMAIL_ENABLED"]
            and form.email.data.lower() != current_user.email.lower()
        ):
            email_changed = True
        form.populate_obj(current_user)
        db.session.add(current_user)
        datastore.mark_changed(id(db.session), uid=current_user.id)
    datastore.commit()

    if email_changed:
        send_confirmation_instructions(current_user)
        # NOTE: Flash message after successful update of profile.
        flash(
            _(
                "Profile was updated. We have sent a verification "
                "email to %(email)s. Please check it.",
                email=current_user.email.lower(),
            ),
            category="success",
        )
    else:
        # NOTE: Flash message after successful update of profile.
        flash(_("Profile was updated."), category="success")


def handle_preferences_form(form):
    """Handle preferences form."""
    form.populate_obj(current_user)
    db.session.add(current_user)
    current_app.extensions["security"].datastore.commit()
    # NOTE: Flash message after successful update of profile.
    flash(_("Preferences were updated."), category="success")

invenio_userprofiles/templates/semantic-ui/invenio_userprofiles/settings/_macros.html
{# -*- coding: utf-8 -*-

  This file is part of Invenio.
  Copyright (C) 2015-2018 CERN.

  Invenio is free software; you can redistribute it and/or modify it
  under the terms of the MIT License; see LICENSE file for more details.
#}

{% macro render_field(field, icon="", placeholder='', autofocus=False, enabled=True, field_class="form-control") %}
  <div class="field {% if field.errors %}error{% endif %}">
    {{ field.label }}
    {%- set extras = dict(autofocus="") if autofocus else dict() %}
    {{field(class_=field_class, disabled=not enabled, placeholder=placeholder, **extras)}}
    {%- if icon %}
    <i class="{{icon}}" aria-hidden="true" ></i>
    {%- endif %}
    {%- if field.description %}
    <small>{{ field.description }}</small>
    {%- endif %}
    {%- if field.errors %}
    <div class="ui negative message" role="alert">
    {%- for error in field.errors %}
    <p>{{error}}</p>
    {% endfor %}
    </div>
    {%- endif %}
  </div>
{% endmacro %}

invenio_userprofiles/templates/semantic-ui/invenio_userprofiles/settings/base.html
{# -*- coding: utf-8 -*-

  This file is part of Invenio.
  Copyright (C) 2015-2018 CERN.

  Invenio is free software; you can redistribute it and/or modify it
  under the terms of the MIT License; see LICENSE file for more details.
#}
{%- extends "invenio_userprofiles/base.html" %}

{%- block page_body %}
{%- block settings_form %}{%- endblock settings_form %}
{%- endblock page_body %}

invenio_userprofiles/templates/semantic-ui/invenio_userprofiles/settings/profile.html
{# -*- coding: utf-8 -*-

  This file is part of Invenio.
  Copyright (C) 2015-2018 CERN.

  Invenio is free software; you can redistribute it and/or modify it
  under the terms of the MIT License; see LICENSE file for more details.
#}
{%- extends config.USERPROFILES_SETTINGS_TEMPLATE %}

{% from "invenio_userprofiles/settings/_macros.html" import render_field, form_errors %}

{% set panel_title = _("Profile") %}
{% set panel_icon = "user icon" %}

{%- block settings_content scoped %}
  <section aria-label="{{ _(panel_title|default('')) }}" class="ui segments">
    <div class="ui segment secondary">

      {%- block settings_content_title scoped %}
        {%- if panel_icon %}

          {%- block settings_content_title_icon scoped %}
            <i class="{{ panel_icon }}" aria-hidden="true"></i>
          {%- endblock %}

        {%- endif %}
        <h2 class="ui tiny header inline-block m-0">{{ panel_title|default("") }}</h2>
      {%- endblock %}

    </div>

    {%- block settings_body scoped %}
      <div class="ui segment">

        {%- block settings_form %}
          {%- if security.confirmable and not current_user.confirmed_at %}
            <form method="POST" role="form">
              {{ verification_form.csrf_token }}
              <div class="ui warning message">
                {{ _("You have not yet verified your email address.") }} {{ verification_form.send_verification_email(class_="compact ui small basic button") }}
              </div>
              <input type="hidden" name="submit" value="verification" />
            </form>
          {%- endif %}

          {%- set form = profile_form %}
          {%- set read_only = config.USERPROFILES_READ_ONLY %}

          <form {% if not read_only %}method="POST"{% endif %} name="profile_form" class="ui form">
            {%- for field in form %}
              {%- if field.widget.input_type == 'hidden' %}
                {{ field() }}
              {%- elif not read_only or "repeat" not in field.id %}
                {{ render_field(field, autofocus=True, enabled=not read_only, placeholder=field.label.text) }}
              {%- endif %}
            {%- endfor %}

            {%- if not read_only %}
              <div class="form-actions">
                <a role="button" href="{{ url_for('invenio_userprofiles.profile') }}" class="ui labeled icon button">
                  <i class="close icon" aria-hidden></i>
                  {{ _('Cancel') }}
                </a>
                <button type="submit" name="submit" value="profile" class="ui primary labeled icon button">
                  <i class="check icon" aria-hidden="true"></i>
                  {{ _('Update profile') }}
                </button>
              </div>
            {%- endif %}
          </form>
        {%- endblock settings_form %}
      </div>
    {%- endblock settings_body %}
    </section>

  <section aria-label="{{ _('Preferences') }}" class="ui segments">
    <div class="ui segment secondary">
      <i class="sliders horizontal icon" aria-hidden="true"></i>
      <h2 class="ui tiny header inline-block m-0">
        {{ _("Preferences") }}
      </h2>
    </div>

    <div class="ui segment">
      {%- set form = preferences_form %}

      <form {% if not read_only %}method="POST"{% endif %} name="preferences_form" class="ui form">
        {%- for field in form %}
          {%- if field.widget.input_type == 'hidden' %}
            {{ field() }}
          {%- elif field.type == 'SelectField' %}
            {{ render_field(field, field_class="ui dropdown") }}
          {%- else %}
            {{ render_field(field, placeholder=field.label.text, field_class="form-control no-dots-list pl-0") }}
          {%- endif %}
        {%- endfor %}

        <div class="form-actions">
          <a role="button" href="{{ url_for('invenio_userprofiles.profile') }}" class="ui labeled icon button">
            <i class="close icon" aria-hidden="true"></i>
            {{ _('Cancel') }}
          </a>
          <button type="submit" name="submit" value="preferences" class="ui primary labeled icon button">
            <i class="check icon" aria-hidden="true"></i>
            {{ _('Update preferences') }}
          </button>
        </div>
      </form>
    </div>
  </section>
{% endblock %}